server:
  port: 10625
spring:
  datasource:
    url: 'jdbc:mysql://sample-db:3306/sample_db'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
  jpa:
    open-in-view: true